alias cls='clear'
alias ls='ls -h --color=always'
alias ll='ls -hl --color=always'
alias lsa='ls -lha --color=always'
alias duh1='du -h --max-depth=1'
alias sudo='sudo '
alias eo='eopkg'
alias publicip='dig +short myip.opendns.com @resolver1.opendns.com'
#alias cmus='gnome-terminal --hide-menubar --geometry=70x40 -- cmus'
alias vi='vim'
alias dcrun='docker-compose -f /docker/compose/docker-compose.yml'
alias dcedit='vi /docker/compose/docker-compose.yml'
alias dclogs='docker-compose -f /docker/compose/docker-compose.yml logs -tf --tail="50"'
alias dlogs='docker logs -tf --tail="50"'
alias doc='docker'
alias signin='ssh-agent ~/bin/sign_in.sh'
alias syncphone='/bin/bash ~/bin/sync-music.sh'
alias dcupdate='/bin/bash ~/bin/update-doc.sh'
